import Head from "next/head";

// import PageRenderer from "../components/renderers/PageRenderer/PageRenderer";

const SlugLandingPage = ({ pageLayout, site }) => {
  console.log("LayooutPage: ", pageLayout);
  console.log("site: ", site);

  return (
    <div>
      <Head>
        <title>{site.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>RENDER PAGE RENDER</p>
      </div>
      {/* <PageRenderer pageLayout={pageLayout} site={site} /> */}
    </div>
  );
};

export async function getServerSideProps(context) {
  const { params } = context;
  console.log("PARAMS: ", params);
  // const pageProps = await fetchPageProps(params);

  // console.log("PAGE PROPS: ", pageProps);

  return {
    props: {
      // ...pageProps,
      pageLayout: "hello",
      site: "site",
    },
  };
}

export default SlugLandingPage;
